const fs = require('fs');

const initialTimeline = [
  { id: 1, name: "The Conception", desc: "A shared idea in a small speakeasy", year: "2019" },
  { id: 2, name: "First Popup", desc: "Taking the concept to the streets of NY", year: "2020" },
  { id: 3, name: "Gallery Opens", desc: "Opening our permanent location in Chelsea", year: "2022" },
  { id: 4, name: "Best Conceptual Bar", desc: "Awarded by NY Bartender Week", year: "2023" },
  { id: 5, name: "The Next Canvas", desc: "Expanding our artist collaboration series", year: "2024" }
];

let sql = `CREATE TABLE "public"."timeline" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "desc" text NOT NULL,
  "year" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);\n\n`;

sql += `INSERT INTO "public"."timeline" ("id", "name", "desc", "year") VALUES\n`;
const values = initialTimeline.map(item => `(${item.id}, '${item.name}', '${item.desc}', '${item.year}')`).join(',\n');
sql += values + `;\n`;

console.log(sql);
